"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "bg" | "en";

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    // Lazy initialization to strictly respect localStorage on first client render if possible
    // This avoids the 'flicker' or state mismatch if the default was hardcoded to "bg"
    const [lang, setLang] = useState<Language>(() => {
        if (typeof window !== "undefined") {
            try {
                const saved = localStorage.getItem("app-language");
                if (saved === "bg" || saved === "en") {
                    return saved;
                }
            } catch (error) {
                console.error("Failed to read language from localStorage:", error);
            }
        }
        return "bg";
    });

    // Ensure document attribute is synced
    useEffect(() => {
        document.documentElement.lang = lang;
        localStorage.setItem("app-language", lang);
    }, [lang]);

    const handleSetLang = (newLang: Language) => {
        setLang(newLang);
    };

    const translations: Record<Language, Record<string, string>> = {
        bg: {
            filters: "Филтри",
            sortBy: "Сортиране",
            search: "Търсене...",
            clear: "Изчисти",
            backToProjects: "← Към всички проекти",
            projectNotFound: "Проектът не е намерен",
            toAllProjects: "Към всички проекти",
            deleteConfirm: "Сигурни ли сте, че искате да изтриете този проект? Това действие е необратимо.",
            projectDeleted: "Проектът беше изтрит успешно",
            deadlineReminder: "Напомняне за краен срок",
            deadlineDays: "Дни преди срока:",
            projectStatusChange: "Промяна на статус на проект",
            projectMemberAdded: "Добавяне към екип",
            mentionInComment: "Споменаване (@mention)",
            newComment: "Нов коментар",
            newCommentDesc: "Във всички ваши задачи (може да е много често)",
            notificationsSaved: "Настройките за известия са запазени",
            notificationsSaveError: "Грешка при запазване",
            myTasks: "Моите Задачи",
            noTasks: "Нямате задачи",
            viewMore: "Виж още",
            myProjects: "Моите Проекти",
            noProjects: "Нямате проекти",
            user: "Потребител",
            tabDashboard: "Табло",
            tabProjects: "Проекти",
            tabTasks: "Задачи",
            tabApprovals: "Одобрения",
            tabTeams: "Екипи",
            tabReports: "Доклади",
            tabSettings: "Настройки",
            tabProfile: "Профил",
            tabAdmin: "Админ",
            tabNotifications: "Известия",
            tabExport: "Експорт",
            deleteError: "Грешка при изтриване на проекта",
            tabTeam: "Екип",
            tabGuests: "Гости",
            tabComments: "Коментари",
            guestsTitle: "Гости",
            inviteGuest: "Покани гост",
            inviteExternalGuest: "Покани външен гост",
            inviteGuestDesc: "Поканете някого извън екипа за сътрудничество по този проект.",
            emailAddress: "Имейл адрес",
            permissions: "Права",
            sendInvite: "Изпрати покана",
            guestAccessDisabled: "Достъпът за гости е изключен",
            guestAccessDisabledDesc: "Този екип не позволява външни гости.",
            noGuests: "Все още няма поканени гости.",
            status: "Статус",
            actions: "Действия",
            guestInvited: "Гостът е поканен успешно",
            guestInviteError: "Грешка при покана на гост",
            guestRemoved: "Гостът е премахнат",
            removeGuestConfirm: "Премахване на този гост?",
            permView: "Преглед на проект",
            permComment: "Коментари",
            permEditTasks: "Редактиране на задачи",
            permCreateTasks: "Създаване на задачи",
            statusActive: "Активен",
            statusPending: "Чакащ",
            statusRevoked: "Отменен",
            profileTitle: "Лична информация",
            profileDesc: "Управлявайте личните си данни и предпочитания",
            fullName: "Пълно име",
            username: "Потребителско име",
            avatarUpload: "Кликнете върху снимката, за да я промените",
            uploading: "Качване...",
            saveChanges: "Запази промените",
            saving: "Запазване...",
            profileUpdated: "Профилът е обновен успешно",
            profileUpdateError: "Грешка при обновяване на профила",
            avatarUpdated: "Профилната снимка е обновена",
            avatarUpdateError: "Неуспешно качване на снимка",
            fileSizeError: "Размерът на файла трябва да е под 5MB",
            notificationsTitle: "Настройки за известия",
            notificationsDesc: "Изберете какви известия искате да получавате",
            taskAssigned: "Назначена задача",
            taskAssignedDesc: "Когато ви бъде назначена нова задача",
            statusChange: "Промяна на статус",
            statusChangeDesc: "Когато статусът на ваша задача се промени",
            taskCompleted: "Завършена задача",
            taskCompletedDesc: "Когато задача, която следите, е завършена",
            priorityChange: "Промяна на приоритет",
            notifications: "Известия",
            markAllAsRead: "Маркирай всички като прочетени",
            noNotifications: "Няма известия",
            now: "Сега",
            minsShort: "мин",
            hoursShort: "ч",
            daysShort: "д",
            searchPlaceholder: "Търсене във всички менюта...",
            noResultsFound: "Няма намерени резултати.",
            pages: "Страници",
            projectsTitle: "Проекти",
            tasksTitle: "Задачи",
            appTitle: "Управление на проекти",
            management: "Управление",
            selectTeam: "Изберете екип",
            searchTeam: "Търсене на екип...",
            noTeamsFound: "Няма намерени екипи.",
            myTeamsTitle: "Моите екипи",
            createTeam: "Създай нов екип",
            roleOwner: "Собственик",
            roleAdmin: "Админ",
            roleMember: "Член",
            // Approvals
            approvalsTitle: "Одобрения",
            approvalsSubtitle: "Управление на заявки за одобрение",
            approvalsSearch: "Търсене на одобрения...",
            newApproval: "Ново одобрение",
            filterAllStatuses: "Всички статуси",
            filterPending: "Чакащи",
            filterApproved: "Одобрени",
            filterRejected: "Отхвърлени",
            filterCancelled: "Отменени",
            typeDocument: "Документ",
            typeDecision: "Решение",
            typeBudget: "Бюджет",
            typeOther: "Друго",
            noApprovals: "Няма намерени одобрения",
            noApprovalsDesc: "Все още няма заявки за одобрение.",
            requestedAt: "Заявено на",
            workflowSequential: "Последователно",
            workflowParallel: "Паралелно",
            // Teams
            teamsTitle: "Екипи",
            teamsSubtitle: "Управление на екипи и членове",
            teamsSearch: "Търсене на екипи...",
            noTeams: "Няма намерени екипи",
            noTeamsDesc: "Създайте първия си екип за да организирате проектите.",
            membersCount: "члена",
            viewTeam: "Преглед",
            inviteMember: "Покани член",
            // Admin
            adminTitle: "Административен панел",
            adminSubtitle: "Управление на системата и одит",
            tabOverview: "Преглед",
            tabUsers: "Потребители",
            tabStatuses: "Статуси",
            tabPriorities: "Приоритети",
            tabLogs: "Одитен Лог",
            statsTotalProjects: "Общо проекти",
            statsActiveProjects: "Активни проекти",
            statsTotalTasks: "Общо задачи",
            statsCompletionRate: "Процент на завършване",
            statsTotalUsers: "Потребители",
            // Task Detail
            taskDetailTitle: "Детайли за задача",
            taskDescription: "Описание",
            taskPriority: "Приоритет",
            taskStatus: "Статус",
            taskAssignee: "Отговорник",
            taskDueDate: "Краен срок",
            taskSubtasks: "Подзадачи",
            taskComments: "Коментари",
            taskDependencies: "Зависимости",
            addComment: "Напишете коментар...",
            addSubtask: "Нова под-задача...",
            noDescription: "Няма предоставено описание.",
            noComments: "Все още няма коментари.",
            noSubtasks: "Няма добавени подзадачи.",
            prioLow: "Нисък",
            prioMedium: "Среден",
            prioHigh: "Висок",
            prioCritical: "Критичен",
            taskFiles: "Файлове",
            taskFileUploaded: "Файлът е прикачен успешно",
            taskFileRemoved: "Файлът е премахнат",
            send: "Изпрати",
            save: "Запази",
            cancel: "Отказ",
            delete: "Изтрий",
            none: "Няма",
            unassigned: "Няма отговорник",
            priority: "Приоритет",
            dueDate: "Краен срок",
            selectDate: "Изберете дата",
            selectPriority: "Изберете приоритет",
            selectStatus: "Изберете статус",
            selectAssignee: "Изберете отговорник",
            taskEditTitle: "Редактирай Задача",
            taskCreateTitle: "Създай Нова Задача",
            taskEditSubtitle: "Обновете детайлите на задачата",
            taskCreateSubtitle: "Попълнете детайлите за да създадете нова задача",
            taskTitleLabel: "Заглавие *",
            taskTitlePlaceholder: "Въведете заглавие на задачата",
            taskDescriptionLabel: "Описание",
            taskDescriptionPlaceholder: "Опишете задачата",
            taskAssigneeLabel: "Отговорник",
            taskEstimatedHoursLabel: "Очаквани Часове",
            taskLabelsLabel: "Етикети",
            taskLabelsPlaceholder: "Добави етикет...",
            taskAttachmentsLabel: "Прикачени файлове",
            taskUploading: "Качване...",
            taskUploadButton: "Качи файлове (макс. 10MB)",
            taskColorLabel: "Цвят",
            taskUpdateButton: "Обнови Задача",
            taskCreateButton: "Създай Задача",
            statusTodo: "За изпълнение",
            statusInProgress: "В процес",
            statusInReview: "В преглед",
            statusDone: "Завършена",
            statusBlocked: "Блокирана",
            titleUpdated: "Заглавието е обновено",
            descriptionUpdated: "Описанието е обновено",
            statusUpdated: "Статусът е променен",
            priorityUpdated: "Приоритетът е променен",
            fileRemoved: "Файлът е премахнат",
            assigneeUpdated: "Отговорникът е променен",
            me: "Аз",
            help: "Помощ",
            subtasksHelpTitle: "Как работят подзадачите:",
            subtasksHelp1: "самостоятелни задачи с описание, етикети и отговорник",
            subtasksHelp2: "прости елементи за отбелязване в рамките на подзадача",
            subtasksHelp3: "Кликнете върху подзадача за да я разширите и видите чеклиста",
            subtasksHelp4: "Използвайте \"+\" за добавяне на нови елементи",
            loadingTask: "Зареждане на задача...",
            taskNotFound: "Задачата не е намерена или е изтрита.",
            close: "Затвори",
            completed: "завършени",
            taskDetailsFor: "Детайли за задача",
            unknownUser: "Непознат потребител",
            taskCommentPlaceholder: "Напишете коментар...",
            dueDateUpdated: "Крайният срок е променен",
            estimatedHoursUpdated: "Прогнозата е обновена",
            colorUpdated: "Цветът е променен",
            loading: "Зареждане...",
            areYouSure: "Сигурни ли сте?",
            subtaskRemoved: "Подзадачата е премахната",
            subtaskUpdated: "Подзадачата е обновена",
            newLabelPlaceholder: "Нов етикет...",
            unassignedPlaceholder: "Без отговорник",
            checklist: "ЧЕКЛИСТ",
            newChecklistItem: "Нова точка",
            addFirstChecklistItem: "+ Добави първа точка към чеклиста",
            newSubtaskPlaceholder: "Заглавие на подзадачата...",
            description: "Описание",
            dependencies: "Зависимости",
            dependencyAdded: "Зависимостта е добавена",
            dependencyRemoved: "Зависимостта е премахната",
            dependencyError: "Грешка при добавяне на зависимост",
            legend: "Легенда",
            noDependencies: "Няма зависимости",
            noDependenciesDesc: "Добавете зависимости за да определите реда на изпълнение",
            addDependency: "Добави зависимост",
            dependsOnTask: "Зависи от задача",
            selectTaskPlaceholder: "Изберете задача...",
            dependencyType: "Тип зависимост",
            noTasksAvailable: "Няма налични задачи",
            dependencyTypes: "Типове зависимости:",
            fsDesc: "Тази задача започва след приключване на избраната",
            ssDesc: "Двете задачи започват заедно",
            ffDesc: "Двете задачи завършват заедно",
            sfDesc: "Избраната задача трябва да започне преди тази да завърши",
            unknownTask: "Неизвестна задача",
            // Kanban Board
            kanbanBoard: "Канбан табло",
            noTasksInColumn: "Няма задачи",
            dropTaskHere: "Пуснете задача тук",
            quickAddTask: "Бързо добавяне",
            addTaskPlaceholder: "Заглавие на задачата...",
            filterByProject: "Филтрирай по проект",
            filterByAssignee: "Филтрирай по изпълнител",
            filterByPriority: "Филтрирай по приоритет",
            myTasks: "Моите задачи",
            allTasks: "Всички задачи",
            allProjects: "Всички проекти",
            allAssignees: "Всички изпълнители",
            allPriorities: "Всички приоритети",
            groupBy: "Групирай по",
            noGrouping: "Без групиране",
            groupByAssignee: "По изпълнител",
            groupByProject: "По проект",
            groupByPriority: "По приоритет",
            taskStatusUpdated: "Статусът на задачата е обновен",
            taskDeleted: "Задачата е изтрита",
            taskMarkedDone: "Задачата е маркирана като завършена",
            view: "Преглед",
            edit: "Редактирай",
            delete: "Изтрий",
            markAsDone: "Маркирай като завършена",
            unassigned: "Неразпределена",
            wipLimitReached: "WIP лимит достигнат",
            taskAdded: "Задачата е добавена",
            error: "Грешка",
            selectProject: "Изберете проект",
            clearFilters: "Изчисти филтрите",
            // Tasks Page Redesign
            tasksTitle: "Задачи",
            tasksSubtitle: "Управлявайте задачите по проекти",
            newTask: "Нова Задача",
            searchTasks: "Търсене на задачи...",
            statsTotal: "Общо",
            statsTodo: "За изпълнение",
            statsInProgress: "В процес",
            statsCompleted: "Завършени",
            statsOverdue: "Просрочени",
            sortNewest: "Най-нови",
            sortOldest: "Най-стари",
            sortName: "Име (А-Я)",
            sortDeadline: "Краен срок",
            sortPriority: "Приоритет",
            viewKanban: "Канбан",
            viewList: "Списък",
            viewCalendar: "Календар",
            noTasksFound: "Няма намерени задачи",
            noTasksDescription: "Създайте нова задача или променете филтрите.",
            status: "Статус",
        },

        en: {
            filters: "Filters",
            sortBy: "Sort By",
            search: "Search...",
            clear: "Clear",
            backToProjects: "← Back to all projects",
            projectNotFound: "Project not found",
            toAllProjects: "To all projects",
            deleteConfirm: "Are you sure you want to delete this project? This action cannot be undone.",
            projectDeleted: "Project deleted successfully",
            deadlineReminder: "Deadline Reminder",
            deadlineDays: "Days before deadline:",
            projectStatusChange: "Project Status Change",
            projectMemberAdded: "Added to Team",
            mentionInComment: "Mention (@mention)",
            newComment: "New Comment",
            newCommentDesc: "In all your tasks (can be very frequent)",
            notificationsSaved: "Notification settings saved",
            notificationsSaveError: "Error saving settings",
            myTasks: "My Tasks",
            noTasks: "No tasks",
            viewMore: "View more",
            myProjects: "My Projects",
            noProjects: "No projects",
            user: "User",
            tabDashboard: "Dashboard",
            tabProjects: "Projects",
            tabTasks: "Tasks",
            tabApprovals: "Approvals",
            tabTeams: "Teams",
            tabReports: "Reports",
            tabSettings: "Settings",
            tabProfile: "Profile",
            tabAdmin: "Admin",
            tabNotifications: "Notifications",
            tabExport: "Export",
            deleteError: "Error deleting project",
            tabTeam: "Team",
            tabGuests: "Guests",
            tabComments: "Comments",
            guestsTitle: "Guests",
            inviteGuest: "Invite Guest",
            inviteExternalGuest: "Invite External Guest",
            inviteGuestDesc: "Invite someone outside the team to collaborate on this project.",
            emailAddress: "Email Address",
            permissions: "Permissions",
            sendInvite: "Send Invitation",
            guestAccessDisabled: "Guest access disabled",
            guestAccessDisabledDesc: "This team does not allow external guests.",
            noGuests: "No guests invited yet.",
            status: "Status",
            actions: "Actions",
            guestInvited: "Guest invited successfully",
            guestInviteError: "Error inviting guest",
            guestRemoved: "Guest removed",
            removeGuestConfirm: "Remove this guest?",
            permView: "View Project",
            permComment: "Comments",
            permEditTasks: "Edit Tasks",
            permCreateTasks: "Create Tasks",
            statusActive: "Active",
            statusPending: "Pending",
            statusRevoked: "Revoked",
            profileTitle: "Personal Information",
            profileDesc: "Manage your personal details and preferences",
            fullName: "Full Name",
            username: "Username",
            avatarUpload: "Click on the photo to change it",
            uploading: "Uploading...",
            saveChanges: "Save Changes",
            saving: "Saving...",
            profileUpdated: "Profile updated successfully",
            profileUpdateError: "Failed to update profile",
            avatarUpdated: "Profile picture updated",
            avatarUpdateError: "Failed to upload picture",
            fileSizeError: "File size must be less than 5MB",
            notificationsTitle: "Notification Settings",
            notificationsDesc: "Choose what notifications you want to receive",
            taskAssigned: "Task Assigned",
            taskAssignedDesc: "When you are assigned a new task",
            statusChange: "Status Change",
            statusChangeDesc: "When the status of your task changes",
            taskCompleted: "Task Completed",
            taskCompletedDesc: "When a task you follow is completed",
            priorityChange: "Priority Change",
            notifications: "Notifications",
            markAllAsRead: "Mark all as read",
            noNotifications: "No notifications",
            now: "Now",
            minsShort: "min",
            hoursShort: "h",
            daysShort: "d",
            searchPlaceholder: "Type a command or search...",
            noResultsFound: "No results found.",
            pages: "Pages",
            projectsTitle: "Projects",
            tasksTitle: "Tasks",
            appTitle: "Project Management",
            management: "Management",
            selectTeam: "Select team",
            searchTeam: "Search team...",
            noTeamsFound: "No teams found.",
            myTeamsTitle: "My teams",
            createTeam: "Create new team",
            roleOwner: "Owner",
            roleAdmin: "Admin",
            roleMember: "Member",
            // Approvals
            approvalsTitle: "Approvals",
            approvalsSubtitle: "Manage approval requests",
            approvalsSearch: "Search approvals...",
            newApproval: "New Approval",
            filterAllStatuses: "All Statuses",
            filterPending: "Pending",
            filterApproved: "Approved",
            filterRejected: "Rejected",
            filterCancelled: "Cancelled",
            typeDocument: "Document",
            typeDecision: "Decision",
            typeBudget: "Budget",
            typeOther: "Other",
            noApprovals: "No approvals found",
            noApprovalsDesc: "There are no approval requests yet.",
            requestedAt: "Requested at",
            workflowSequential: "Sequential",
            workflowParallel: "Parallel",
            // Teams
            teamsTitle: "Teams",
            teamsSubtitle: "Manage teams and members",
            teamsSearch: "Search teams...",
            noTeams: "No teams found",
            noTeamsDesc: "Create your first team to organize projects.",
            membersCount: "members",
            viewTeam: "View",
            inviteMember: "Invite member",
            // Admin
            adminTitle: "Admin Panel",
            adminSubtitle: "System management and audit",
            tabOverview: "Overview",
            tabUsers: "Users",
            tabStatuses: "Statuses",
            tabPriorities: "Priorities",
            tabLogs: "Audit Log",
            statsTotalProjects: "Total Projects",
            statsActiveProjects: "Active Projects",
            statsTotalTasks: "Total Tasks",
            statsCompletionRate: "Completion Rate",
            statsTotalUsers: "Total Users",
            // Task Detail
            taskDetailTitle: "Task Details",
            taskDescription: "Description",
            taskPriority: "Priority",
            taskStatus: "Status",
            taskAssignee: "Assignee",
            taskDueDate: "Due Date",
            taskSubtasks: "Subtasks",
            taskComments: "Comments",
            taskDependencies: "Dependencies",
            addComment: "Write a comment...",
            addSubtask: "New subtask...",
            noDescription: "No description provided.",
            noComments: "No comments yet.",
            noSubtasks: "No subtasks added.",
            prioLow: "Low",
            prioMedium: "Medium",
            prioHigh: "High",
            prioCritical: "Critical",
            taskFiles: "Files",
            taskFileUploaded: "File uploaded successfully",
            taskFileRemoved: "File removed",
            send: "Send",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            none: "None",
            unassigned: "Unassigned",
            priority: "Priority",
            dueDate: "Due Date",
            selectDate: "Select date",
            selectPriority: "Select priority",
            selectStatus: "Select status",
            selectAssignee: "Select assignee",
            taskEditTitle: "Edit Task",
            taskCreateTitle: "Create New Task",
            taskEditSubtitle: "Update the details of the task",
            taskCreateSubtitle: "Fill in the details to create a new task",
            taskTitleLabel: "Title *",
            taskTitlePlaceholder: "Enter task title",
            taskDescriptionLabel: "Description",
            taskDescriptionPlaceholder: "Describe the task",
            taskAssigneeLabel: "Assignee",
            taskEstimatedHoursLabel: "Estimated Hours",
            taskLabelsLabel: "Labels",
            taskLabelsPlaceholder: "Add label...",
            taskAttachmentsLabel: "Attachments",
            taskUploading: "Uploading...",
            taskUploadButton: "Upload files (max 10MB)",
            taskColorLabel: "Color",
            taskUpdateButton: "Update Task",
            taskCreateButton: "Create Task",
            statusTodo: "To Do",
            statusInProgress: "In Progress",
            statusInReview: "In Review",
            statusDone: "Done",
            statusBlocked: "Blocked",
            titleUpdated: "Title updated",
            descriptionUpdated: "Description updated",
            statusUpdated: "Status updated",
            priorityUpdated: "Priority updated",
            fileRemoved: "File removed",
            assigneeUpdated: "Assignee updated",
            me: "Me",
            help: "Help",
            subtasksHelpTitle: "How subtasks work:",
            subtasksHelp1: "independent tasks with description, labels and assignee",
            subtasksHelp2: "simple checklist items within a subtask",
            subtasksHelp3: "Click on subtask to expand and view checklist",
            subtasksHelp4: "Use \"+\" to add new items",
            loadingTask: "Loading task...",
            taskNotFound: "Task not found or deleted.",
            close: "Close",
            completed: "completed",
            taskDetailsFor: "Details for task",
            unknownUser: "Unknown user",
            taskCommentPlaceholder: "Write a comment...",
            dueDateUpdated: "Due date updated",
            estimatedHoursUpdated: "Estimated hours updated",
            colorUpdated: "Color updated",
            loading: "Loading...",
            areYouSure: "Are you sure?",
            subtaskRemoved: "Subtask removed",
            subtaskUpdated: "Subtask updated",
            newLabelPlaceholder: "New label...",
            unassignedPlaceholder: "Unassigned",
            checklist: "CHECKLIST",
            newChecklistItem: "New item",
            addFirstChecklistItem: "+ Add first item to checklist",
            newSubtaskPlaceholder: "Subtask title...",
            description: "Description",
            dependencies: "Dependencies",
            dependencyAdded: "Dependency added",
            dependencyRemoved: "Dependency removed",
            dependencyError: "Error adding dependency",
            legend: "Legend",
            noDependencies: "No dependencies",
            noDependenciesDesc: "Add dependencies to define execution order",
            addDependency: "Add dependency",
            dependsOnTask: "Depends on task",
            selectTaskPlaceholder: "Select task...",
            dependencyType: "Dependency type",
            noTasksAvailable: "No tasks available",
            dependencyTypes: "Dependency types:",
            fsDesc: "This task starts after the selected one finishes",
            ssDesc: "Both tasks start together",
            ffDesc: "Both tasks finish together",
            sfDesc: "The selected task must start before this one finishes",
            unknownTask: "Unknown task",
            // Kanban Board
            kanbanBoard: "Kanban Board",
            noTasksInColumn: "No tasks",
            dropTaskHere: "Drop task here",
            quickAddTask: "Quick add",
            addTaskPlaceholder: "Task title...",
            filterByProject: "Filter by project",
            filterByAssignee: "Filter by assignee",
            filterByPriority: "Filter by priority",
            myTasks: "My Tasks",
            allTasks: "All Tasks",
            allProjects: "All Projects",
            allAssignees: "All Assignees",
            allPriorities: "All Priorities",
            groupBy: "Group by",
            noGrouping: "No grouping",
            groupByAssignee: "By assignee",
            groupByProject: "By project",
            groupByPriority: "By priority",
            taskStatusUpdated: "Task status updated",
            taskDeleted: "Task deleted",
            taskMarkedDone: "Task marked as done",
            view: "View",
            edit: "Edit",
            delete: "Delete",
            markAsDone: "Mark as done",
            unassigned: "Unassigned",
            wipLimitReached: "WIP limit reached",
            taskAdded: "Task added",
            error: "Error",
            selectProject: "Select project",
            clearFilters: "Clear filters",
            // Tasks Page Redesign
            tasksTitle: "Tasks",
            tasksSubtitle: "Manage tasks across projects",
            newTask: "New Task",
            searchTasks: "Search tasks...",
            statsTotal: "Total",
            statsTodo: "To Do",
            statsInProgress: "In Progress",
            statsCompleted: "Completed",
            statsOverdue: "Overdue",
            sortNewest: "Newest",
            sortOldest: "Oldest",
            sortName: "Name (A-Z)",
            sortDeadline: "Deadline",
            sortPriority: "Priority",
            viewKanban: "Kanban",
            viewList: "List",
            viewCalendar: "Calendar",
            noTasksFound: "No tasks found",
            noTasksDescription: "Create a new task or adjust your filters.",
            status: "Status",
        }
    };

    const t = (key: string) => {
        return translations[lang][key] || key;
    };


    return (
        <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
